name: Building blocks
on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello, world!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: say goodbye
        run: |
            echo "This step will fail"
            exit 1 
      - name: say goodbye
        run: echo "Goodbye, world!"