name: System Report
on: push

jobs:
  system-report:
    runs-on: ubuntu-latest
    steps:
      - name: OS and kernel information
        run: |
            uname -a
            uname -r
      - name: Disk usage
        run: |
            df -h
      - name: Current date and time
        run: |
            date
      - name: installing tree
        run: |
            sudo apt-get update
            sudo apt-get install -y tree
      - name: Directory structure
        run: |
            tree -L 2
  tool-check:
    runs-on: ubuntu-latest
    steps:
      - name: install jq
        run: sudo apt-get install jq -y
      - name: create report.json
        run: |
            echo '{"tool1": "installed"}' > report.json
            echo '{"tool2": "installed"}' >> report.json
            echo '{"tool3": "installed"}' >> report.json